### ISSUE TITLE
The Daemon is intefering with OBS Audio Device Capture

### ISSUE THREAD

**Issue by HadetTheUndying** [DavidRisch/steamvr_utils#13]
When using OBS the Daemon will constantly switch my input devices back to the Radio Mic. We need a way to disable this portion of the switching as I cannot use steamvr_utils while streaming now. Even newly added capture sources have this issue. Specifically it will automatically set my desktop capture to the Radio Mic instead of the HDMI output and changing it in pavucontrol will see it change right back the next time the daemon makes it's check

**Comment by DavidRisch** [comment]
The automatic switching of any audio sources can be disabled, from config_template.yaml:
```yaml
change_source: true  # Boolean. Automatically change the source (microphone).
```
Alternatively you could add 'obs' to `excluded_clients_regexes`, that would stop steamvr_utils from changing sinks+sources of OBS specifically. This solution would still switch the source of any other application, but ignore OBS. Both solutions should fix your problem.

All of the behavior you described is intentional as the program does not know OBS is not a game. I will add some better documentation on how my implementation audio switching works and what some unintended consequences can be.

**Comment by HadetTheUndying** [comment]
Awesome thanks. I'll give this a try tonight

**Comment by DavidRisch** [comment]
Added documentation in eac1eaa3
